# Generated by Django 4.2.2 on 2023-08-17 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoList',
            fields=[
                ('work_status', models.CharField(choices=[('P', 'Pending'), ('IP', 'In Process'), ('C', 'Completed')], default='P', max_length=2)),
                ('sn', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
            ],
        ),
    ]
