# Generated by Django 4.2.2 on 2023-08-18 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_alter_todolist_work_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='work_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Process', 'In Process'), ('Completed', 'Completed')], default='Pending', max_length=100, null=True),
        ),
    ]
